### ISSUE TITLE
Not rendering correctly in 5760x1080

### ISSUE THREAD

**Issue by JvPeek** [ibid-11962/Windows-95-3D-Maze-Screensaver#3]
I know, it's a bit of a niche case but the walls tend to clip at 5760x1080 resolutions.
![2021-01-12-071259_5760x1080_scrot](https://user-images.githubusercontent.com/71159838/104276823-eef06100-54a5-11eb-8304-191474877d2d.png)

**Comment by ibid-11962** [comment]
I was able to replicate this by setting the chrome resolution, and I think it should be fixed by just decreasing the value of `near` on line 33 of `maze.js`.

7983996419cefc6728ac9f66549af011e71e5428

Let me know if this fixed the issue for you.

I'm not really maintaining this repo anymore, so I can't do much beyond that.
