### ISSUE TITLE
I'm an Idiot; how to I run this project locally?

### ISSUE THREAD

**Issue by 2DRudy** [ibid-11962/Windows-95-3D-Maze-Screensaver#4]
Like the title says, I have the repository downloaded but where do I go from there?
I also have Java and Firefox installed, so what do I need to do next?

**Comment by ibid-11962** [comment]
You  do not need Java installed (this repo uses *JavaScript*, not Java) and everything here should run natively in a web browser. The only issue is that it's considered a security falw to allow JavaScript to access local files, so you need to set up a file server. I mentioned Firefox in the readme because at the time Firefox didn't follow that security practice correctly. They've since corrected it, so that's no longer an option.

If you have python installed then you can follow [the directions here](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server) to serve the folder. Also [see here](https://gist.github.com/willurd/5720255) for a list of commands to start local file servers with other languages.

If you'd rather a non command line option, [this chrome extension](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en) should work. I'm sure there are plenty of other options as well.
